spring:
  datasource:
    url: jdbc:postgresql://db:5432/resume
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate # never use update in real projects
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
