sspring:
  datasource:
    url: jdbc:postgresql://db:5432/resume
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    ignore-unsupported-databases: true


logging:
  level:
    org.flywaydb.core: DEBUG


