package com.fb2devs.slopsitebackend.model; 

import jakarta.persistence.*;

@Entity //this marks our class as a JPA (our ORM) entity
@Table(name="students")
public class Student {
  @Id //marks as primary key of entity
  @GeneratedValue(strategy = GenerationType.IDENTITY) //indicating this value is generated by db IDENTITY column
  private Long id;

  @Column(nullable = false, unique = true)
  private String username;

  @Column(nullable = false)
  private String password;

  @Column(nullable = false)
  private String name;

  // default constructor required by JPA
  public Student() {
  }

  // constructor w/ fields
  public Student(String username, String password, String name) {
    this.username = username;
    this.password = password;
    this.name = name;
  }

  // da gettas and settas
  public Long getId() {
    return id;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getPassword() {
    return password; 
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  // equals and hashcode methods for proper object comparision
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
  }
}



// poop bro
// override stuff???
// look at Trae chat
//chatgpt name - mainchat4slopsite
